### ISSUE TITLE
🌟 [server] Matching API

### ISSUE THREAD

**Issue by Meow520** [Doer-org/hack-camp_vol4_2023-1#77]
## What
matching APIの大枠を作って欲しいです。
APIのデータ構造はfigma参照で
マッチングするアルゴリズムの実装以外の部分
元からマッチングの情報が作成されている体で一旦実装する

## 順序
- User_idからFriend_id, Hangout_name(3つ), Schedule_date(3つ)
- hangoutの3つをforで回して一つづつhangoutに一致するUser_Idをとってくる
- scheduleの3つをforで回して一つづつdateに一致するUser_Idをとってくる
- Friendから出たID、hangoutからでたID、scheduleからでたIDの３つの配列に全て入っているIDを配列で返す

## todo
- [x] `internal/domain/entity/matching.go`
        friend_idをAPIのデータ値として持つ
- [x] `internal/domain/repository/matching.go`
        GetMatchinByUserId(user_id)を定義する
- [x] `internal/usecase/matching.go`
       GetMatchinByUserId(user_id)の入力エラーと出力の定義
- [x] `internal/infrastructure/repository/matching.go`
       repositoryで必要なDtoを実装してください
- [x] `internal/infrastructure/repository/matching.go`
　　順序を参考に実装お願いします
- [x] `web/http/handler/matching.go`
- [x] `web/http/json/matching.go`
- [x] `web/router/matching.go`
- [x] `cmd/router.go`

## reference
[Mahiroさんのテンプレート](https://github.com/mahiro72/go_api-template)

## do date
8/12
