### ISSUE TITLE
🌟 [server] Friend APIでFriendのNameをとってくる

### ISSUE THREAD

**Issue by Meow520** [Doer-org/hack-camp_vol4_2023-1#90]
## What
GetFriendByUserIdとGetRequestsByFriendIdでFriendのNameとイメージをとってくる

## todo
- [x] `internal/domain/entity/friend.go`
       FriendById -> Friendに入っているデータ＋FriendName＋FriendImage
- [x] `internal/infra../repo../dto/friend,go`
       FriendByIdDto 同じ感じで
- [x] `internal/infra../repo../friend.go`
       GetFriendByUserIdとGetRequestsByFriendIdでNameをとる
　　INNER JOINを使う
- [x] `web/http/json/friend.go`
       FriendByIdJson 同じ感じで！

## 献上品
`SELECT friend.id, friend.user_id, friend.friend_id, friend.accept, user.name, user.image 
    FROM friend 
    INNER JOIN user ON friend.friend_id = user.id
    WHERE user_id = ? AND accept = true`

## reference
[参照先](https://github.com/Doer-org/glyph/blob/dev/server/internal/infrastructure/persistance/comment.go)

## do date
いつまでにするのか？
